server:
  port: 10001
  servlet:
    context-path: /v1.x

spring:
  application:
    name: tsf-container-web
## swagger setting
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
swagger:
  enabled: true
  title: Web RESTFul API
  description: Container Platform Web API
  version: 2.9.2
  base-package: com.tencent.tsf.container
  base-path: /**

## rancher setting
container:
  platform:
    rancher:
      #Rancher API请求地址
      endpoint: https://172.31.49.238/v3
rancher:
  kubernetes-engine:
    addonJobTimeout: 31
    services:
      etcd:
        retention: 73h
        snapshot: true
        extraArgs:
          heartbeat-interval: 501
          election-timeout: 5001
logging:
  level:
    root: debug